[Starling App]
Id=chrome
Name=Chrome
Kind=host
Order=80
Glyph=chrome
Color=F2F3F5
Exec=chrome
Install=chrome
Bins=/opt/google/chrome/chrome
DesktopEntry=google-chrome;google-chrome-stable;com.google.Chrome;chromium;chromium-browser
WmClass=google-chrome;Google-chrome;chrome
DebUrl=https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
DebMarker=opt/google/chrome/chrome
Category=Browsers
Publisher=Google
Subtitle=Google's own browser
Size=117 MB
Description=The real Google Chrome — account sync, Widevine and Google integration, installed from Google's official package (which keeps itself updated through apt).
