[Starling App]
Id=vscode
Name=VS Code
Kind=host
Order=90
Glyph=vscode
Color=2B3242
Exec=vscode
Install=vscode
Bins=/usr/bin/code;/usr/share/code/code;/snap/bin/code
DesktopEntry=code;visual-studio-code;code-oss;codium;vscodium
WmClass=Code;code;code-oss;VSCodium
DebUrl=https://update.code.visualstudio.com/latest/linux-deb-x64/stable
DebMarker=usr/share/code/code
Category=Develop
Publisher=Microsoft
Subtitle=Code editing. Redefined.
Size=232 MB
Description=Microsoft's official build — the extension marketplace, settings sync and remote development. Installed from Microsoft's apt repository, so `apt upgrade` keeps it current. Note this is the branded build, which is proprietary; the MIT licence covers the source, not the binary.
