// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// MARK: - UniqueWidget

/// Base class for stateful widgets that have exactly one inflated instance in
/// the tree.
///
/// Such widgets must be given a `GlobalKey`. This key can be generated by the
/// subclass from its type, e.g. by using a `GlobalObjectKey`.
///
/// Since only one instance can be inflated at a time, there is only ever one
/// corresponding `State` object. That object is exposed, for convenience, via
/// the `currentState` property.
///
/// When subclassing `UniqueWidget`, provide the corresponding `State` subclass
/// as the type argument.
///
/// **Dart Source:** `packages/flutter/lib/src/widgets/unique_widget.dart:20-37`
open class UniqueWidget<T: State<StatefulWidget>>: StatefulWidget {

    /// Creates a widget that has exactly one inflated instance in the tree.
    ///
    /// The `key` argument is required because it identifies the unique inflated
    /// instance of this widget.
    ///
    /// **Dart Source:** `unique_widget.dart:25`
    public init(key: GlobalKey<T>) {
        super.init(key: key)
    }

    /// Creates the mutable state for this widget.
    ///
    /// **Dart Source:** `unique_widget.dart:28`
    open override func createState() -> State<StatefulWidget> {
        fatalError("Subclasses of UniqueWidget must override createState()")
    }

    /// The state for the unique inflated instance of this widget.
    ///
    /// Might be nil if the widget is not currently in the tree.
    ///
    /// **Dart Source:** `unique_widget.dart:33-36`
    public var currentState: T? {
        guard let globalKey = key as? GlobalKey<T> else { return nil }
        return globalKey.currentState
    }
}
